// lib/patterns.ts
// 책 "필수회화구문 140" 목차/구문을 사진에서 직접 옮긴 데이터 (1~140 전체)
export interface Dialogue {
  speaker: "E" | "K";
  text_en: string;
  text_ko: string;
}

export interface PatternData {
  id: number;
  chapter_num: number;
  chapter_title: string;
  pattern_ko: string;
  pattern_en: string;
  example_dialogue: Dialogue[];
}

export const CHAPTER_TITLES: Record<number, string> = {
  1: "자주 보지만 막상 말하려면 생각이 안 나는 동사관련 구문",
  2: "자주 보지만 막상 말하려면 생각이 안 나는 기타 구문",
  3: "영어식으로 발상이 안 되기 때문에 사용하기 어려운 구문",
  4: "12가지 특수 구문",
  5: "기본 단어만 알면 쉽게 사용할 수 있는 구문",
  6: "실수할까 봐 두려운 구문 & 문법은 맞지만 아무도 그렇게 말하지 않는 구문",
  7: "관용적으로 외워두면 좋은 구문과 표현",
};

export const PATTERNS: PatternData[] = [
  {
    id: 1,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "~일 것 같다",
    pattern_en: "be likely to ~",
    example_dialogue: [
      { speaker: "E", text_en: "It's likely to rain this afternoon.", text_ko: "오후에 비가 올 것 같아." },
      { speaker: "K", text_en: "Then let's take an umbrella.", text_ko: "그럼 우산을 챙기자." },
    ],
  },
  {
    id: 2,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "계속 ~하다",
    pattern_en: "keep -ing",
    example_dialogue: [
      { speaker: "E", text_en: "Don't give up. Keep trying!", text_ko: "포기하지 마. 계속 노력해!" },
      { speaker: "K", text_en: "Okay, I'll keep trying.", text_ko: "알겠어, 계속 해 볼게." },
    ],
  },
  {
    id: 3,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "~를 하려고 한다",
    pattern_en: "intend to ~",
    example_dialogue: [
      { speaker: "E", text_en: "What do you intend to do after graduation?", text_ko: "졸업 후에 뭐 할 작정이야?" },
      { speaker: "K", text_en: "I intend to study abroad.", text_ko: "유학 갈 생각이야." },
    ],
  },
  {
    id: 4,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "주저 말고 ~하세요",
    pattern_en: "feel free to ~",
    example_dialogue: [
      { speaker: "E", text_en: "Feel free to ask me anything.", text_ko: "뭐든 편하게 물어보세요." },
      { speaker: "K", text_en: "Thank you, that's very kind.", text_ko: "감사합니다, 정말 친절하시네요." },
    ],
  },
  {
    id: 5,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "…이거나 ~이다",
    pattern_en: "either … or ~",
    example_dialogue: [
      { speaker: "E", text_en: "You can have either coffee or tea.", text_ko: "커피나 차 중에 드시면 돼요." },
      { speaker: "K", text_en: "I'll take coffee, please.", text_ko: "커피로 할게요." },
    ],
  },
  {
    id: 6,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "빨리 ~하고 싶어",
    pattern_en: "can't wait to ~",
    example_dialogue: [
      { speaker: "E", text_en: "I can't wait to see the new movie.", text_ko: "새 영화 빨리 보고 싶어." },
      { speaker: "K", text_en: "Me too! Let's go this weekend.", text_ko: "나도! 이번 주말에 가자." },
    ],
  },
  {
    id: 7,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "…하느니 차라리 ~하겠다",
    pattern_en: "would rather ~ than …",
    example_dialogue: [
      { speaker: "E", text_en: "I would rather stay home than go out.", text_ko: "나가느니 차라리 집에 있겠어." },
      { speaker: "K", text_en: "Same here. I'm tired.", text_ko: "나도 그래. 피곤해." },
    ],
  },
  {
    id: 8,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "꼭 ~해라",
    pattern_en: "be sure to ~",
    example_dialogue: [
      { speaker: "E", text_en: "Be sure to lock the door.", text_ko: "꼭 문을 잠가." },
      { speaker: "K", text_en: "Don't worry, I will.", text_ko: "걱정 마, 그럴게." },
    ],
  },
  {
    id: 9,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "~했어야 했는데",
    pattern_en: "should have + PP",
    example_dialogue: [
      { speaker: "E", text_en: "I should have studied harder.", text_ko: "더 열심히 공부했어야 했는데." },
      { speaker: "K", text_en: "It's not too late to start now.", text_ko: "지금 시작해도 늦지 않았어." },
    ],
  },
  {
    id: 10,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "~할 자격이 없다",
    pattern_en: "not deserve ~",
    example_dialogue: [
      { speaker: "E", text_en: "He doesn't deserve such praise.", text_ko: "그는 그런 칭찬을 받을 자격이 없어." },
      { speaker: "K", text_en: "I agree, he didn't do much.", text_ko: "맞아, 한 게 별로 없잖아." },
    ],
  },
  {
    id: 11,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "내가 ~해줄게",
    pattern_en: "Let me ~",
    example_dialogue: [
      { speaker: "E", text_en: "Let me help you with that.", text_ko: "내가 그거 도와줄게." },
      { speaker: "K", text_en: "Thanks, I appreciate it.", text_ko: "고마워, 정말 고마워." },
    ],
  },
  {
    id: 12,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "~의 가치가 있다",
    pattern_en: "be worth ~",
    example_dialogue: [
      { speaker: "E", text_en: "This book is worth reading.", text_ko: "이 책은 읽을 가치가 있어." },
      { speaker: "K", text_en: "Then I'll borrow it.", text_ko: "그럼 빌려야겠다." },
    ],
  },
  {
    id: 13,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "우연히 ~하게 되다",
    pattern_en: "happen to ~",
    example_dialogue: [
      { speaker: "E", text_en: "I happened to meet her at the store.", text_ko: "우연히 가게에서 그녀를 만났어." },
      { speaker: "K", text_en: "What a coincidence!", text_ko: "정말 우연이네!" },
    ],
  },
  {
    id: 14,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "~인지 모르겠어요?",
    pattern_en: "Can't you see ~?",
    example_dialogue: [
      { speaker: "E", text_en: "Can't you see I'm busy?", text_ko: "나 바쁜 거 안 보여?" },
      { speaker: "K", text_en: "Sorry, I'll come back later.", text_ko: "미안, 나중에 올게." },
    ],
  },
  {
    id: 15,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "점점 ~해진다",
    pattern_en: "be getting ~",
    example_dialogue: [
      { speaker: "E", text_en: "It's getting colder these days.", text_ko: "요즘 점점 추워지고 있어." },
      { speaker: "K", text_en: "Yeah, winter is coming.", text_ko: "응, 겨울이 오고 있어." },
    ],
  },
  {
    id: 16,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "~한 것으로 판명되다",
    pattern_en: "It turned out (that) ~",
    example_dialogue: [
      { speaker: "E", text_en: "It turned out that he was right.", text_ko: "그가 옳았던 것으로 판명됐어." },
      { speaker: "K", text_en: "Really? I didn't expect that.", text_ko: "정말? 예상 못 했네." },
    ],
  },
  {
    id: 17,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "~한 것이 마음에 걸리다",
    pattern_en: "I feel bad (that) ~",
    example_dialogue: [
      { speaker: "E", text_en: "I feel bad that I forgot your birthday.", text_ko: "네 생일을 잊은 게 마음에 걸려." },
      { speaker: "K", text_en: "It's okay, don't worry about it.", text_ko: "괜찮아, 신경 쓰지 마." },
    ],
  },
  {
    id: 18,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "~할 돈이 없다",
    pattern_en: "can't afford to ~",
    example_dialogue: [
      { speaker: "E", text_en: "I want to buy the new iPhone, but it's too expensive.", text_ko: "새 아이폰 사고 싶은데 너무 비싸네." },
      { speaker: "K", text_en: "Yeah, I can't afford to spend that much money right now either.", text_ko: "맞아, 나도 지금은 그만큼 큰돈을 쓸 여유가 없어." },
      { speaker: "E", text_en: "Are you coming to the party tonight?", text_ko: "오늘 밤 파티에 올 거야?" },
      { speaker: "K", text_en: "I wish I could, but I can't afford to waste any time. I have an exam tomorrow.", text_ko: "가고 싶지만 시간을 낭비할 여유가 없어. 내일 시험이 있거든." },
    ],
  },
  {
    id: 19,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "~하기로 되어 있다",
    pattern_en: "be supposed to ~",
    example_dialogue: [
      { speaker: "E", text_en: "What time are we meeting tomorrow?", text_ko: "우리 내일 몇 시에 만나기로 했지?" },
      { speaker: "K", text_en: "We are supposed to meet at the coffee shop at 10 AM.", text_ko: "오전 10시에 커피숍에서 만나기로 되어 있어." },
      { speaker: "E", text_en: "You aren't supposed to smoke inside this building.", text_ko: "이 건물 안에서는 담배를 피우면 안 됩니다." },
      { speaker: "K", text_en: "Oh, I'm sorry. I didn't see the sign.", text_ko: "아, 죄송합니다. 표지판을 못 봤네요." },
    ],
  },
  {
    id: 20,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "~한지 봅시다",
    pattern_en: "see ~",
    example_dialogue: [
      { speaker: "E", text_en: "Is the laptop still working?", text_ko: "노트북 아직 잘 작동해?" },
      { speaker: "K", text_en: "Let me see if it turns on properly.", text_ko: "전원이 잘 켜지는지 한번 볼게." },
      { speaker: "E", text_en: "Do we have enough milk for breakfast?", text_ko: "우리 아침 먹을 우유 충분히 있나?" },
      { speaker: "K", text_en: "I'll check the refrigerator and see.", text_ko: "냉장고를 확인해서 알아볼게." },
    ],
  },
  {
    id: 21,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "~하면서 …했다",
    pattern_en: "did …, doing ~",
    example_dialogue: [
      { speaker: "E", text_en: "How did you spend your weekend?", text_ko: "주말 어떻게 보냈어?" },
      { speaker: "K", text_en: "I just stayed home, watching movies all day.", text_ko: "그냥 집에 머물면서 하루 종일 영화 봤어." },
      { speaker: "E", text_en: "He hurt his ankle while playing basketball yesterday.", text_ko: "그는 어제 농구 하다가 발목을 다쳤어." },
      { speaker: "K", text_en: "Oh, that's too bad. Is he okay now?", text_ko: "아, 안됐다. 지금은 괜찮대?" },
    ],
  },
  {
    id: 22,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "~인 채로 두다",
    pattern_en: "leave + 목적어 + ~",
    example_dialogue: [
      { speaker: "E", text_en: "Don't leave the door open. It's freezing outside.", text_ko: "문 열어둔 채로 두지 마. 밖이 엄청 추워." },
      { speaker: "K", text_en: "Sorry, I'll close it right away.", text_ko: "미안, 바로 닫을게." },
      { speaker: "E", text_en: "Why did you leave the lights on all night?", text_ko: "왜 밤새 불을 켜둔 채로 둔 거야?" },
      { speaker: "K", text_en: "I fell asleep while reading a book.", text_ko: "책 읽다가 잠들어서 그랬어." },
    ],
  },
  {
    id: 23,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "~한 것 같진 않아",
    pattern_en: "I doubt (that) ~",
    example_dialogue: [
      { speaker: "E", text_en: "Do you think it will rain tomorrow?", text_ko: "내일 비가 올 것 같아?" },
      { speaker: "K", text_en: "I doubt that it will rain. The sky is completely clear.", text_ko: "비가 올 것 같지는 않아. 하늘이 완전히 맑거든." },
      { speaker: "E", text_en: "Will he show up on time for the meeting?", text_ko: "그가 회의에 제시간에 나타날까?" },
      { speaker: "K", text_en: "I doubt it. He is always late.", text_ko: "그럴 리가 없어. 그는 항상 늦잖아." },
    ],
  },
  {
    id: 24,
    chapter_num: 1,
    chapter_title: CHAPTER_TITLES[1],
    pattern_ko: "~처럼 보인다",
    pattern_en: "It appears (that) ~",
    example_dialogue: [
      { speaker: "E", text_en: "It appears that there is a problem with the server.", text_ko: "서버에 문제가 생긴 것처럼 보입니다." },
      { speaker: "K", text_en: "Let's call the IT department right now.", text_ko: "지금 바로 IT 부서에 연락해 봅시다." },
      { speaker: "E", text_en: "She looks very happy today.", text_ko: "그녀는 오늘 무척 행복해 보이네." },
      { speaker: "K", text_en: "Yes, it appears she passed the final interview.", text_ko: "응, 최종 면접에 합격한 것 같아." },
    ],
  },
  {
    id: 25,
    chapter_num: 2,
    chapter_title: CHAPTER_TITLES[2],
    pattern_ko: "그렇지 않으면 ~",
    pattern_en: "otherwise ~",
    example_dialogue: [
      { speaker: "E", text_en: "Hurry up, otherwise we'll be late.", text_ko: "서둘러, 그렇지 않으면 늦어." },
      { speaker: "K", text_en: "Okay, I'm coming.", text_ko: "알겠어, 가고 있어." },
    ],
  },
  {
    id: 26,
    chapter_num: 2,
    chapter_title: CHAPTER_TITLES[2],
    pattern_ko: "…한 게 아니라 ~한 거다",
    pattern_en: "It's not that …, it's just that ~",
    example_dialogue: [
      { speaker: "E", text_en: "It's not that I don't like it, it's just that I'm full.", text_ko: "싫어서가 아니라 그냥 배불러서 그래." },
      { speaker: "K", text_en: "I see, no worries.", text_ko: "그렇구나, 괜찮아." },
    ],
  },
  {
    id: 27,
    chapter_num: 2,
    chapter_title: CHAPTER_TITLES[2],
    pattern_ko: "~해 주시면 감사하겠습니다",
    pattern_en: "I'd appreciate it if S + would ~",
    example_dialogue: [
      { speaker: "E", text_en: "I'd appreciate it if you would help me.", text_ko: "도와주시면 감사하겠습니다." },
      { speaker: "K", text_en: "Of course, gladly.", text_ko: "물론이죠, 기꺼이요." },
    ],
  },
  {
    id: 28,
    chapter_num: 2,
    chapter_title: CHAPTER_TITLES[2],
    pattern_ko: "~라고 가정해 봐",
    pattern_en: "suppose S + V",
    example_dialogue: [
      { speaker: "E", text_en: "Suppose you won the lottery.", text_ko: "네가 복권에 당첨됐다고 가정해 봐." },
      { speaker: "K", text_en: "I'd travel the world!", text_ko: "세계 여행을 할 거야!" },
    ],
  },
  {
    id: 29,
    chapter_num: 2,
    chapter_title: CHAPTER_TITLES[2],
    pattern_ko: "…할 수 있도록 ~하다",
    pattern_en: "~ so that S can …",
    example_dialogue: [
      { speaker: "E", text_en: "Speak slowly so that I can understand.", text_ko: "알아들을 수 있도록 천천히 말해줘." },
      { speaker: "K", text_en: "Sure, is this better?", text_ko: "그래, 이게 나아?" },
    ],
  },
  {
    id: 30,
    chapter_num: 2,
    chapter_title: CHAPTER_TITLES[2],
    pattern_ko: "…한 것 중에 가장 ~한 것이다",
    pattern_en: "the -est ~ I've ever + PP",
    example_dialogue: [
      { speaker: "E", text_en: "This is the best meal I've ever had.", text_ko: "이건 내가 먹어본 것 중 최고야." },
      { speaker: "K", text_en: "I'm glad you like it.", text_ko: "마음에 든다니 다행이야." },
    ],
  },
  {
    id: 31,
    chapter_num: 2,
    chapter_title: CHAPTER_TITLES[2],
    pattern_ko: "~가 어떻게 됐어?",
    pattern_en: "How did ~ go?",
    example_dialogue: [
      { speaker: "E", text_en: "How did your interview go?", text_ko: "면접 어떻게 됐어?" },
      { speaker: "K", text_en: "It went really well!", text_ko: "정말 잘됐어!" },
    ],
  },
  {
    id: 32,
    chapter_num: 2,
    chapter_title: CHAPTER_TITLES[2],
    pattern_ko: "…한 것은 ~이다",
    pattern_en: "What S + V is ~",
    example_dialogue: [
      { speaker: "E", text_en: "I'm not sure if I can complete this project by myself.", text_ko: "이 프로젝트를 나 혼자 끝낼 수 있을지 잘 모르겠어." },
      { speaker: "K", text_en: "Don't worry. What you need is a little bit of help from others.", text_ko: "걱정 마. 네게 필요한 것은 다른 사람들의 약간의 도움이야." },
      { speaker: "E", text_en: "Did you understand what the professor said today?", text_ko: "오늘 교수님이 하신 말씀 이해했어?" },
      { speaker: "K", text_en: "Not really. What he meant was completely unclear to me.", text_ko: "아니 전혀. 그가 의미한 것은 나에게 완전히 모호했어." },
    ],
  },
  {
    id: 33,
    chapter_num: 2,
    chapter_title: CHAPTER_TITLES[2],
    pattern_ko: "(단지) …라고는 ~뿐이다",
    pattern_en: "All S + V is ~",
    example_dialogue: [
      { speaker: "E", text_en: "How can I start using this new software?", text_ko: "이 새 소프트웨어는 어떻게 쓰기 시작하면 돼?" },
      { speaker: "K", text_en: "It's very simple. All you have to do is enter your email address here.", text_ko: "아주 간단해. 넌 여기 이메일 주소를 입력하기만 하면 돼." },
      { speaker: "E", text_en: "What did you buy at the shopping mall yesterday?", text_ko: "어제 쇼핑몰에서 뭐 샀어?" },
      { speaker: "K", text_en: "All I bought was a cheap T-shirt. Nothing else.", text_ko: "내가 산 거라고는 저렴한 티셔츠 한 장뿐이야. 다른 건 없어." },
    ],
  },
  {
    id: 34,
    chapter_num: 2,
    chapter_title: CHAPTER_TITLES[2],
    pattern_ko: "~일지도 모르니까",
    pattern_en: "In case S + V",
    example_dialogue: [
      { speaker: "E", text_en: "The weather looks a bit unstable today.", text_ko: "오늘 날씨가 좀 불안정해 보이네." },
      { speaker: "K", text_en: "Take an umbrella with you in case it rains this afternoon.", text_ko: "오후에 비가 올지도 모르니까 우산을 챙겨가." },
      { speaker: "E", text_en: "Why are you bringing two credit cards?", text_ko: "신용카드를 왜 두 장이나 챙겨?" },
      { speaker: "K", text_en: "Just in case one of them doesn't work.", text_ko: "혹시 하나가 안 될 경우를 대비해서 그런 거야." },
    ],
  },
  {
    id: 35,
    chapter_num: 3,
    chapter_title: CHAPTER_TITLES[3],
    pattern_ko: "~하게 되다",
    pattern_en: "get + 형용사/PP",
    example_dialogue: [
      { speaker: "E", text_en: "We should hurry up. It's getting dark outside.", text_ko: "우리 서둘러야겠어. 밖이 어두워지고 있어." },
      { speaker: "K", text_en: "You're right. Let's head back to the car.", text_ko: "맞아. 자동차로 돌아가자." },
      { speaker: "E", text_en: "Why did he leave the party so early?", text_ko: "그는 왜 이렇게 파티에서 일찍 가버린 거야?" },
      { speaker: "K", text_en: "He got bored with the conversation.", text_ko: "대화가 지루해졌거든." },
    ],
  },
  {
    id: 36,
    chapter_num: 3,
    chapter_title: CHAPTER_TITLES[3],
    pattern_ko: "~라고 들었어요",
    pattern_en: "I was told (that) ~",
    example_dialogue: [
      { speaker: "E", text_en: "Have you met the new manager yet?", text_ko: "새로 오신 매니저님 아직 안 만나봤지?" },
      { speaker: "K", text_en: "No, but I was told that he is very strict.", text_ko: "응, 하지만 그분이 엄청 엄격하시다고 들었어." },
      { speaker: "E", text_en: "Is the famous Italian restaurant still open?", text_ko: "그 유명한 이탈리아 레스토랑 아직도 영업해?" },
      { speaker: "K", text_en: "I was told they closed down last month.", text_ko: "지난달에 문을 닫았다고 들었어." },
    ],
  },
  {
    id: 37,
    chapter_num: 3,
    chapter_title: CHAPTER_TITLES[3],
    pattern_ko: "왜 ~?",
    pattern_en: "What makes ~?",
    example_dialogue: [
      { speaker: "E", text_en: "What makes you think he will change his mind?", text_ko: "무엇 때문에 그가 마음을 바꿀 거라고 생각하는 거야?" },
      { speaker: "K", text_en: "Because he looked quite hesitant during the meeting.", text_ko: "회의 중에 꽤 망설이는 것처럼 보였거든." },
      { speaker: "E", text_en: "You look exceptionally happy today. What makes you so excited?", text_ko: "너 오늘 유난히 행복해 보인다. 무엇이 너를 그렇게 신나게 만든 거야?" },
      { speaker: "K", text_en: "I just found out that I got a promotion!", text_ko: "나 방금 승진했다는 소식을 알게 됐거든!" },
    ],
  },
  {
    id: 38,
    chapter_num: 3,
    chapter_title: CHAPTER_TITLES[3],
    pattern_ko: "~한지 얼마나 됐어요?",
    pattern_en: "How long have S + PP?",
    example_dialogue: [
      { speaker: "E", text_en: "Your English is so natural. How long have you lived in the US?", text_ko: "영어 발음이 정말 자연스럽네. 미국에 사신 지 얼마나 되셨어요?" },
      { speaker: "K", text_en: "I've been living here for about five years now.", text_ko: "이제 한 5년 정도 살았어요." },
      { speaker: "E", text_en: "This building looks incredibly old.", text_ko: "이 건물은 정말 믿기지 않을 정도로 오래되어 보이네." },
      { speaker: "K", text_en: "How long has it been since it was built?", text_ko: "지어진 지 얼마나 된 걸까?" },
    ],
  },
  {
    id: 39,
    chapter_num: 3,
    chapter_title: CHAPTER_TITLES[3],
    pattern_ko: "꼭 ~할게요",
    pattern_en: "I promise ~",
    example_dialogue: [
      { speaker: "E", text_en: "Please don't tell anyone about what I just said.", text_ko: "내가 방금 한 말 아무한테도 말하지 마." },
      { speaker: "K", text_en: "I promise I won't tell a soul. Your secret is safe with me.", text_ko: "아무에게도 말 안 하겠다고 약속할게. 비밀 지켜줄게." },
      { speaker: "E", text_en: "You are late again! We missed the beginning of the movie.", text_ko: "너 또 늦었어! 영화 시작 부분을 놓쳤잖아." },
      { speaker: "K", text_en: "I'm really sorry. I promise to be on time next time.", text_ko: "정말 미안해. 다음엔 꼭 제시간에 오겠다고 약속할게." },
    ],
  },
  {
    id: 40,
    chapter_num: 3,
    chapter_title: CHAPTER_TITLES[3],
    pattern_ko: "~해서야 비로소 …했다",
    pattern_en: "not … until ~",
    example_dialogue: [
      { speaker: "E", text_en: "Did you know that the library was closed yesterday?", text_ko: "어제 도서관 문 닫았던 거 알았어?" },
      { speaker: "K", text_en: "No, I didn't realize it until I arrived at the entrance.", text_ko: "아니, 입구에 도착해서야 비로소 알았어." },
      { speaker: "E", text_en: "When did you find your lost wallet?", text_ko: "잃어버린 지갑은 언제 찾았어?" },
      { speaker: "K", text_en: "It was not until this morning that I found it under my bed.", text_ko: "오늘 아침이 되어서야 비로소 침대 밑에서 찾았어." },
    ],
  },
  {
    id: 41,
    chapter_num: 3,
    chapter_title: CHAPTER_TITLES[3],
    pattern_ko: "~에 가본 적이 있다",
    pattern_en: "have been to ~",
    example_dialogue: [
      { speaker: "E", text_en: "Have you ever traveled to Europe?", text_ko: "유럽 여행 가본 적 있어?" },
      { speaker: "K", text_en: "Yes, I have been to Paris and London twice.", text_ko: "응, 파리랑 런던에 두 번 가본 적 있어." },
      { speaker: "E", text_en: "Is that new art gallery downtown any good?", text_ko: "시내에 새로 생긴 미술관 괜찮아?" },
      { speaker: "K", text_en: "I'm not sure. I haven't been to that place yet.", text_ko: "잘 모르겠어. 난 아직 거기에 안 가봤거든." },
    ],
  },
  {
    id: 42,
    chapter_num: 3,
    chapter_title: CHAPTER_TITLES[3],
    pattern_ko: "~라고 쓰여 있다",
    pattern_en: "It says ~",
    example_dialogue: [
      { speaker: "E", text_en: "What does the sign over there mean?", text_ko: "저기 있는 표지판이 무슨 뜻이야?" },
      { speaker: "K", text_en: "It says \"No Parking\" in big bold letters.", text_ko: "큰 굵은 글씨로 \"주차 금지\"라고 쓰여 있어." },
      { speaker: "E", text_en: "Did you read the email from the HR department?", text_ko: "인사부에서 온 이메일 읽어봤어?" },
      { speaker: "K", text_en: "Yes, it says the office will be closed this Friday.", text_ko: "응, 이번 주 금요일에 사무실 휴무라고 쓰여 있더라." },
    ],
  },
  {
    id: 43,
    chapter_num: 3,
    chapter_title: CHAPTER_TITLES[3],
    pattern_ko: "~를 가진 사람",
    pattern_en: "a person with ~",
    example_dialogue: [
      { speaker: "E", text_en: "Who is the man talking to the CEO right now?", text_ko: "지금 대표님이랑 이야기 나누고 있는 저 남자는 누구야?" },
      { speaker: "K", text_en: "He is a person with extensive experience in international trade.", text_ko: "국제 무역 분야에서 풍부한 경험을 가진 사람이야." },
      { speaker: "E", text_en: "I need someone to help me translate this document.", text_ko: "이 서류 번역을 도와줄 사람이 필요해." },
      { speaker: "K", text_en: "You should look for a person who is fluent in both Korean and English.", text_ko: "한국어와 영어 모두에 능통한 사람을 찾아봐." },
    ],
  },
  {
    id: 44,
    chapter_num: 3,
    chapter_title: CHAPTER_TITLES[3],
    pattern_ko: "내가 ~하기에는",
    pattern_en: "My ~ is to/that …",
    example_dialogue: [
      { speaker: "E", text_en: "What is your primary goal for this quarter?", text_ko: "이번 분기 네 가장 주요한 목표가 뭐야?" },
      { speaker: "K", text_en: "My goal is to increase our online sales by twenty percent.", text_ko: "내 목표는 온라인 매출을 20% 성장시키는 거야." },
      { speaker: "E", text_en: "Is there any problem with the final report?", text_ko: "최종 보고서에 무슨 문제라도 있어?" },
      { speaker: "K", text_en: "My only concern is that the budget might be slightly tight.", text_ko: "내 유일한 걱정은 예산이 다소 타이트할 수도 있다는 점이야." },
    ],
  },
  {
    id: 45,
    chapter_num: 3,
    chapter_title: CHAPTER_TITLES[3],
    pattern_ko: "~에 의하면",
    pattern_en: "From what ~",
    example_dialogue: [
      { speaker: "E", text_en: "Is the company performance improving this year?", text_ko: "올해 회사 실적이 좀 나아지고 있어?" },
      { speaker: "K", text_en: "From what I've heard, the revenue has grown significantly.", text_ko: "내가 들은 바에 의하면, 매출이 크게 늘었다고 하더라고." },
      { speaker: "E", text_en: "Do you think she will accept our offer?", text_ko: "그녀가 우리 제안을 받아들일까?" },
      { speaker: "K", text_en: "From what I can see, she seems very interested in this position.", text_ko: "내가 보기에는, 이 직무에 관심이 아주 많아 보여." },
    ],
  },
  {
    id: 46,
    chapter_num: 4,
    chapter_title: CHAPTER_TITLES[4],
    pattern_ko: "만약 ~라면",
    pattern_en: "If S + V(과거), S + would ~",
    example_dialogue: [
      { speaker: "E", text_en: "Do you want to go to the concert tonight?", text_ko: "오늘 밤 콘서트 가고 싶어?" },
      { speaker: "K", text_en: "I'd love to, but if I had more money, I would buy a ticket.", text_ko: "가고 싶지만, 돈이 더 있다면 티켓을 살 텐데." },
      { speaker: "E", text_en: "Why don't you ask her out?", text_ko: "그녀에게 데이트 신청해 보는 건 어때?" },
      { speaker: "K", text_en: "If I were braver, I would ask her. But I'm too nervous.", text_ko: "내가 더 용감하다면 신청할 텐데. 너무 떨려." },
    ],
  },
  {
    id: 47,
    chapter_num: 4,
    chapter_title: CHAPTER_TITLES[4],
    pattern_ko: "만약 ~했더라면",
    pattern_en: "If S + had + PP, S + would have + PP",
    example_dialogue: [
      { speaker: "E", text_en: "Did you catch the train yesterday?", text_ko: "어제 기차 제시간에 탔어?" },
      { speaker: "K", text_en: "No, if I had woken up earlier, I would have caught it.", text_ko: "아니, 내가 더 일찍 일어났다면 탔을 텐데." },
      { speaker: "E", text_en: "How was the exam?", text_ko: "시험 어땠어?" },
      { speaker: "K", text_en: "It was tough. If I had studied harder, I would have passed it.", text_ko: "어려웠어. 공부를 더 열심히 했다면 합격했을 텐데." },
    ],
  },
  {
    id: 48,
    chapter_num: 4,
    chapter_title: CHAPTER_TITLES[4],
    pattern_ko: "만약 ~했더라면",
    pattern_en: "If S + had + PP, S + would + V",
    example_dialogue: [
      { speaker: "E", text_en: "Are you still looking for your keys?", text_ko: "아직도 열쇠 찾고 있어?" },
      { speaker: "K", text_en: "Yes. If I had put them on the table yesterday, I would know where they are now.", text_ko: "응. 어제 테이블 위에 두었더라면 지금 어디 있는지 알 텐데." },
      { speaker: "E", text_en: "You look really tired today.", text_ko: "너 오늘 정말 피곤해 보인다." },
      { speaker: "K", text_en: "If I had slept more last night, I would feel better now.", text_ko: "어젯밤에 잠을 더 잤더라면 지금 컨디션이 더 좋을 텐데." },
    ],
  },
  {
    id: 49,
    chapter_num: 4,
    chapter_title: CHAPTER_TITLES[4],
    pattern_ko: "~하면",
    pattern_en: "If ~",
    example_dialogue: [
      { speaker: "E", text_en: "If it rains tomorrow, the picnic will be canceled.", text_ko: "내일 비가 오면 소풍은 취소될 거야." },
      { speaker: "K", text_en: "Let's check the weather forecast tonight.", text_ko: "오늘 밤에 일기예보를 확인해 보자." },
      { speaker: "E", text_en: "If you need any help, please let me know.", text_ko: "도움이 필요하시면 언제든 말씀해 주세요." },
      { speaker: "K", text_en: "Thank you. I appreciate your kindness.", text_ko: "감사합니다. 친절에 감사드려요." },
    ],
  },
  {
    id: 50,
    chapter_num: 4,
    chapter_title: CHAPTER_TITLES[4],
    pattern_ko: "틀림없이 ~했을 거야",
    pattern_en: "must have + PP",
    example_dialogue: [
      { speaker: "E", text_en: "The streets are completely wet.", text_ko: "길이 완전히 젖었네." },
      { speaker: "K", text_en: "It must have rained heavily while we were inside.", text_ko: "우리가 안에 있는 동안 비가 많이 왔음에 틀림없어." },
      { speaker: "E", text_en: "She passed the difficult exam with a perfect score.", text_ko: "그녀는 그 어려운 시험을 만점으로 통과했대." },
      { speaker: "K", text_en: "Wow, she must have studied incredibly hard.", text_ko: "와, 공부를 정말 열심히 했음에 틀림없네." },
    ],
  },
  {
    id: 51,
    chapter_num: 4,
    chapter_title: CHAPTER_TITLES[4],
    pattern_ko: "~한 것",
    pattern_en: "the thing that ~",
    example_dialogue: [
      { speaker: "E", text_en: "What is the most important thing to you?", text_ko: "너에게 가장 중요한 게 뭐야?" },
      { speaker: "K", text_en: "The thing that matters most to me is my family's health.", text_ko: "나에게 가장 중요한 것은 가족의 건강이야." },
      { speaker: "E", text_en: "I don't understand why he acts like that.", text_ko: "그는 왜 저렇게 행동하는지 이해가 안 가." },
      { speaker: "K", text_en: "What he needs is just a little bit of attention.", text_ko: "그에게 필요한 것은 단지 아주 조그만 관심뿐이야." },
    ],
  },
  {
    id: 52,
    chapter_num: 4,
    chapter_title: CHAPTER_TITLES[4],
    pattern_ko: "~하는 사람",
    pattern_en: "a person who ~",
    example_dialogue: [
      { speaker: "E", text_en: "Who is your role model?", text_ko: "네 롤모델이 누구야?" },
      { speaker: "K", text_en: "I respect a person who never gives up on their dreams.", text_ko: "나는 꿈을 절대 포기하지 않는 사람을 존경해." },
      { speaker: "E", text_en: "We need a new team leader for this project.", text_ko: "이번 프로젝트를 이끌 새 팀장이 필요해." },
      { speaker: "K", text_en: "We should choose a person who has strong communication skills.", text_ko: "소통 능력이 뛰어난 사람을 선택해야 해." },
    ],
  },
  {
    id: 53,
    chapter_num: 4,
    chapter_title: CHAPTER_TITLES[4],
    pattern_ko: "~조차 하지 않다",
    pattern_en: "not even ~",
    example_dialogue: [
      { speaker: "E", text_en: "Did you enjoy the movie last night?", text_ko: "어젯밤에 영화 재미있게 봤어?" },
      { speaker: "K", text_en: "No, it was so boring that I didn't even finish watching it.", text_ko: "아니, 너무 지루해서 끝까지 보지도 않았어." },
      { speaker: "E", text_en: "Does he know about the schedule change?", text_ko: "그가 일정 바뀐 거 알고 있어?" },
      { speaker: "K", text_en: "No, he doesn't even answer my phone calls.", text_ko: "아니, 내 전화조차 받지 않아." },
    ],
  },
  {
    id: 54,
    chapter_num: 4,
    chapter_title: CHAPTER_TITLES[4],
    pattern_ko: "단지 ~하다",
    pattern_en: "just ~",
    example_dialogue: [
      { speaker: "E", text_en: "Why did you call me so late?", text_ko: "왜 이렇게 늦게 전화했어?" },
      { speaker: "K", text_en: "I just wanted to hear your voice.", text_ko: "그냥 단지 네 목소리가 듣고 싶어서 그랬어." },
      { speaker: "E", text_en: "Are you buying that expensive jacket?", text_ko: "그 비싼 재킷 살 거야?" },
      { speaker: "K", text_en: "No, I'm just looking around the store.", text_ko: "아니, 그냥 단지 가게를 둘러보는 중이야." },
    ],
  },
  {
    id: 55,
    chapter_num: 4,
    chapter_title: CHAPTER_TITLES[4],
    pattern_ko: "~할 리 없다",
    pattern_en: "There is no reason (that) ~",
    example_dialogue: [
      { speaker: "E", text_en: "There is no reason to be afraid of making mistakes.", text_ko: "실수하는 것을 두려워할 이유가 전혀 없어." },
      { speaker: "K", text_en: "You're right. That's how we learn.", text_ko: "맞아. 그렇게 배우는 거지." },
      { speaker: "E", text_en: "He said he forgot his own birthday.", text_ko: "그가 자기 생일을 잊어버렸다고 하더라고." },
      { speaker: "K", text_en: "That can't be true. He must be joking.", text_ko: "그럴 리가 없어. 농담하는 게 분명해." },
    ],
  },
  {
    id: 56,
    chapter_num: 4,
    chapter_title: CHAPTER_TITLES[4],
    pattern_ko: "~가 있을 예정이다",
    pattern_en: "There is going to be ~",
    example_dialogue: [
      { speaker: "E", text_en: "Why is the office so busy today?", text_ko: "오늘 왜 이렇게 사무실이 분주하지?" },
      { speaker: "K", text_en: "There is going to be a big presentation this afternoon.", text_ko: "오늘 오후에 큰 발표가 있을 예정이거든." },
      { speaker: "E", text_en: "Are you doing anything special this weekend?", text_ko: "이번 주말에 특별한 계획 있어?" },
      { speaker: "K", text_en: "There is going to be a food festival downtown. I might check it out.", text_ko: "시내에서 푸드 페스티벌이 열릴 예정이야. 한번 가볼까 해." },
    ],
  },
  {
    id: 57,
    chapter_num: 4,
    chapter_title: CHAPTER_TITLES[4],
    pattern_ko: "~가 있는 것 같다",
    pattern_en: "There seems to be ~",
    example_dialogue: [
      { speaker: "E", text_en: "Why isn't the internet working?", text_ko: "인터넷이 왜 안 되지?" },
      { speaker: "K", text_en: "There seems to be a problem with the Wi-Fi router.", text_ko: "와이파이 공유기에 문제가 있는 것 같아." },
      { speaker: "E", text_en: "The atmosphere in the meeting room was tense.", text_ko: "회의실 분위기가 살벌하더라고." },
      { speaker: "K", text_en: "Yes, there seems to be a misunderstanding between the managers.", text_ko: "응, 매니저들 사이에 오해가 좀 있는 것 같아." },
    ],
  },
  {
    id: 58,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "~라고 확신하다",
    pattern_en: "I'm sure (that) ~",
    example_dialogue: [
      { speaker: "E", text_en: "I'm sure that you'll do great.", text_ko: "네가 잘할 거라고 확신해." },
      { speaker: "K", text_en: "Thanks for the support.", text_ko: "응원 고마워." },
    ],
  },
  {
    id: 59,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "~라던데 정말 그런가요?",
    pattern_en: "I heard (that) ~, is that so?",
    example_dialogue: [
      { speaker: "E", text_en: "I heard you're moving, is that so?", text_ko: "이사 간다던데 정말 그래요?" },
      { speaker: "K", text_en: "Yes, next month.", text_ko: "네, 다음 달에요." },
    ],
  },
  {
    id: 60,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "그건 ~에 달려 있다",
    pattern_en: "It depends on ~",
    example_dialogue: [
      { speaker: "E", text_en: "It depends on the weather.", text_ko: "그건 날씨에 달려 있어." },
      { speaker: "K", text_en: "Let's hope it's sunny.", text_ko: "맑길 바라자." },
    ],
  },
  {
    id: 61,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "난 ~할까 생각중이야",
    pattern_en: "I'm thinking of ~",
    example_dialogue: [
      { speaker: "E", text_en: "I'm thinking of changing jobs.", text_ko: "난 이직할까 생각 중이야." },
      { speaker: "K", text_en: "Really? Why?", text_ko: "정말? 왜?" },
    ],
  },
  {
    id: 62,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "~인지 아세요?",
    pattern_en: "Do you know ~?",
    example_dialogue: [
      { speaker: "E", text_en: "Do you know where the station is?", text_ko: "역이 어디인지 아세요?" },
      { speaker: "K", text_en: "Yes, it's that way.", text_ko: "네, 저쪽이에요." },
    ],
  },
  {
    id: 63,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "~이 궁금하군",
    pattern_en: "I wonder ~",
    example_dialogue: [
      { speaker: "E", text_en: "I wonder if she's okay.", text_ko: "그녀가 괜찮은지 궁금하군." },
      { speaker: "K", text_en: "Let's give her a call.", text_ko: "전화해 보자." },
    ],
  },
  {
    id: 64,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "~때문에 전화 드렸습니다",
    pattern_en: "I'm calling about ~",
    example_dialogue: [
      { speaker: "E", text_en: "I'm calling about the apartment.", text_ko: "아파트 때문에 전화 드렸습니다." },
      { speaker: "K", text_en: "Sure, how can I help?", text_ko: "네, 무엇을 도와드릴까요?" },
    ],
  },
  {
    id: 65,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "~하려고 한 건 아니다",
    pattern_en: "I didn't mean to ~",
    example_dialogue: [
      { speaker: "E", text_en: "I didn't mean to hurt you.", text_ko: "너에게 상처 주려던 건 아니었어." },
      { speaker: "K", text_en: "It's okay, I know.", text_ko: "괜찮아, 알아." },
    ],
  },
  {
    id: 66,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "내가 ~하려면",
    pattern_en: "If I'm going to ~",
    example_dialogue: [
      { speaker: "E", text_en: "If I'm going to do this, I'll do it right.", text_ko: "내가 이걸 하려면 제대로 할 거야." },
      { speaker: "K", text_en: "That's the spirit.", text_ko: "바로 그거야." },
    ],
  },
  {
    id: 67,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "~인 척하다",
    pattern_en: "pretend ~",
    example_dialogue: [
      { speaker: "E", text_en: "He pretended not to hear me.", text_ko: "그는 내 말을 못 들은 척했어." },
      { speaker: "K", text_en: "That's frustrating.", text_ko: "답답하네." },
    ],
  },
  {
    id: 68,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "~하려고 하다",
    pattern_en: "try to ~",
    example_dialogue: [
      { speaker: "E", text_en: "I'll try to finish it today.", text_ko: "오늘 끝내려고 해볼게." },
      { speaker: "K", text_en: "Take your time.", text_ko: "천천히 해." },
    ],
  },
  {
    id: 69,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "~이라니 믿을 수가 없어",
    pattern_en: "I can't believe (that) ~",
    example_dialogue: [
      { speaker: "E", text_en: "I can't believe we won!", text_ko: "우리가 이겼다니 믿을 수가 없어!" },
      { speaker: "K", text_en: "It's amazing!", text_ko: "정말 대단해!" },
    ],
  },
  {
    id: 70,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "비록 …이라도 얼마나 ~하겠니?",
    pattern_en: "Even though …, how ~?",
    example_dialogue: [
      { speaker: "E", text_en: "Even though he's busy, how kind he is!", text_ko: "비록 바빠도 그는 얼마나 친절한지!" },
      { speaker: "K", text_en: "He really is.", text_ko: "정말 그래." },
    ],
  },
  {
    id: 71,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "~이라면 얼마나 좋을까?",
    pattern_en: "How wonderful it would be if ~?",
    example_dialogue: [
      { speaker: "E", text_en: "How wonderful it would be if we could fly!", text_ko: "날 수 있다면 얼마나 좋을까!" },
      { speaker: "K", text_en: "Like a dream.", text_ko: "꿈만 같지." },
    ],
  },
  {
    id: 72,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "~할 때마다",
    pattern_en: "Every time ~",
    example_dialogue: [
      { speaker: "E", text_en: "Every time I see her, she smiles.", text_ko: "그녀를 볼 때마다 미소를 지어." },
      { speaker: "K", text_en: "She's so cheerful.", text_ko: "정말 밝다." },
    ],
  },
  {
    id: 73,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "~일까 봐 무섭다",
    pattern_en: "I'm scared (that) ~",
    example_dialogue: [
      { speaker: "E", text_en: "I'm scared that I'll fail.", text_ko: "떨어질까 봐 무서워." },
      { speaker: "K", text_en: "You'll be fine, trust me.", text_ko: "잘될 거야, 믿어." },
    ],
  },
  {
    id: 74,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "…할까 봐 ~했다",
    pattern_en: "I was afraid (that) …, so ~",
    example_dialogue: [
      { speaker: "E", text_en: "I was afraid it would rain, so I brought an umbrella.", text_ko: "비가 올까 봐 우산을 가져왔어." },
      { speaker: "K", text_en: "Smart move.", text_ko: "잘했네." },
    ],
  },
  {
    id: 75,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "~든 상관 안 한다",
    pattern_en: "I don't care ~",
    example_dialogue: [
      { speaker: "E", text_en: "What color do you want for the new couch?", text_ko: "새 소파 색상 어떤 걸로 원해?" },
      { speaker: "K", text_en: "I don't care what color it is, as long as it's comfortable.", text_ko: "편하기만 하다면 무슨 색이든 난 상관 없어." },
      { speaker: "E", text_en: "People might talk about your choice.", text_ko: "사람들이 네 선택에 대해 수군거릴지도 몰라." },
      { speaker: "K", text_en: "I don't care what they think of me.", text_ko: "그들이 나를 어떻게 생각하든 난 신경 안 써." },
    ],
  },
  {
    id: 76,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "…하는 이유는 ~때문이다",
    pattern_en: "The reason … is that ~",
    example_dialogue: [
      { speaker: "E", text_en: "Why are you so late today?", text_ko: "너 오늘 왜 이렇게 늦었어?" },
      { speaker: "K", text_en: "The reason I'm late is that I got stuck in heavy traffic.", text_ko: "내가 늦은 이유는 교통 체증에 가로막혔기 때문이야." },
      { speaker: "E", text_en: "Why did she decline the job offer?", text_ko: "그녀는 왜 그 일자리 제안을 거절한 거야?" },
      { speaker: "K", text_en: "The reason she declined is that the salary was too low.", text_ko: "거절한 이유는 연봉이 너무 낮았기 때문이래." },
    ],
  },
  {
    id: 77,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "~부터 …하고 있다",
    pattern_en: "have been -ing since ~",
    example_dialogue: [
      { speaker: "E", text_en: "You look exhausted. What have you been doing?", text_ko: "너 진이 빠져 보인다. 뭐 하고 있었어?" },
      { speaker: "K", text_en: "I have been working on this report since early this morning.", text_ko: "오늘 이른 아침부터 줄곧 이 보고서를 붙잡고 일해오고 있어." },
      { speaker: "E", text_en: "Do you know how to play the piano?", text_ko: "피아노 칠 줄 알아?" },
      { speaker: "K", text_en: "Yes, I have been playing the piano since I was seven years old.", text_ko: "응, 일곱 살 때 이후로 줄곧 피아노를 쳐왔어." },
    ],
  },
  {
    id: 78,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "~한 게 있다면",
    pattern_en: "If there is anything ~",
    example_dialogue: [
      { speaker: "E", text_en: "I'm moving to my new apartment tomorrow.", text_ko: "나 내일 새 아파트로 이사해." },
      { speaker: "K", text_en: "If there is anything I can do to help, just let me know.", text_ko: "내가 도울 수 있는 일이 있다면 뭐든 편하게 말해줘." },
      { speaker: "E", text_en: "Thank you for organizing the event.", text_ko: "행사를 준비해 주셔서 감사합니다." },
      { speaker: "K", text_en: "If there is anything you are not satisfied with, please tell us.", text_ko: "혹시라도 만족스럽지 못한 부분이 있다면 저희에게 말씀해 주세요." },
    ],
  },
  {
    id: 79,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "여기 ~한 게 있다",
    pattern_en: "Here's what ~",
    example_dialogue: [
      { speaker: "E", text_en: "We need a plan to finish this by Friday.", text_ko: "금요일까지 이걸 끝내려면 계획이 필요해." },
      { speaker: "K", text_en: "Okay, here's what we are going to do first.", text_ko: "좋아, 우리가 먼저 할 일은 바로 이것이야." },
      { speaker: "E", text_en: "What did the doctor tell you about your health?", text_ko: "의사가 네 건강에 대해 뭐라고 하셔?" },
      { speaker: "K", text_en: "Here's what he said: I need to get more sleep.", text_ko: "의사가 말한 건 바로 이거야. 잠을 더 자야 한대." },
    ],
  },
  {
    id: 80,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "~같은",
    pattern_en: "such as ~",
    example_dialogue: [
      { speaker: "E", text_en: "What kind of hobbies do you enjoy?", text_ko: "어떤 종류의 취미를 즐겨?" },
      { speaker: "K", text_en: "I like outdoor activities, such as hiking and camping.", text_ko: "하이킹이나 캠핑과 같은 야외 활동을 좋아해." },
      { speaker: "E", text_en: "We need to avoid eating unhealthy foods.", text_ko: "우리는 건강에 좋지 않은 음식을 먹는 것을 피해야 해." },
      { speaker: "K", text_en: "Right, foods such as fast food and sugary drinks.", text_ko: "맞아, 패스트푸드나 당분이 많은 음료 같은 식품들 말이지." },
    ],
  },
  {
    id: 81,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "~처럼/~같은",
    pattern_en: "like ~",
    example_dialogue: [
      { speaker: "E", text_en: "She sings so beautifully.", text_ko: "그녀는 노래를 정말 아름답게 부른다." },
      { speaker: "K", text_en: "Yeah, she sings like a professional angel.", text_ko: "응, 마치 프로 천사처럼 노래해." },
      { speaker: "E", text_en: "Why are you acting like a child?", text_ko: "너 왜 아이처럼 행동하고 그래?" },
      { speaker: "K", text_en: "I'm just really excited about the trip!", text_ko: "여행 때문에 너무 신나서 그렇지!" },
    ],
  },
  {
    id: 82,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "~이라는 감이 오다",
    pattern_en: "I have a feeling (that) ~",
    example_dialogue: [
      { speaker: "E", text_en: "Do you think we will win the match today?", text_ko: "오늘 우리 경기에서 이길 것 같아?" },
      { speaker: "K", text_en: "I have a feeling that today is our lucky day.", text_ko: "오늘은 우리의 운이 좋은 날이라는 느낌이 들어." },
      { speaker: "E", text_en: "He didn't say much during dinner.", text_ko: "그는 저녁 식사 동안 말을 별로 안 하더라." },
      { speaker: "K", text_en: "I have a feeling he is hiding something from us.", text_ko: "그가 우리에게 무언가를 숨기고 있다는 느낌이 드네." },
    ],
  },
  {
    id: 83,
    chapter_num: 5,
    chapter_title: CHAPTER_TITLES[5],
    pattern_ko: "그게 바로 ~한 것이다",
    pattern_en: "That's what ~",
    example_dialogue: [
      { speaker: "E", text_en: "I think we should focus on customer service.", text_ko: "우리가 고객 서비스에 집중해야 한다고 생각해." },
      { speaker: "K", text_en: "Exactly! That's what I've been trying to say.", text_ko: "정확해! 그것이 바로 내가 계속 말하려던 바야." },
      { speaker: "E", text_en: "Why did you buy that expensive watch?", text_ko: "왜 그렇게 비싼 시계를 산 거야?" },
      { speaker: "K", text_en: "That's what I wanted for my birthday.", text_ko: "그게 바로 내 생일에 내가 원했던 것이거든." },
    ],
  },
  {
    id: 84,
    chapter_num: 6,
    chapter_title: CHAPTER_TITLES[6],
    pattern_ko: "~을 못 참겠다",
    pattern_en: "I can't stand ~",
    example_dialogue: [
      { speaker: "E", text_en: "I can't stand this noise.", text_ko: "이 소음을 못 참겠어." },
      { speaker: "K", text_en: "Let's go somewhere quiet.", text_ko: "조용한 데로 가자." },
    ],
  },
  {
    id: 85,
    chapter_num: 6,
    chapter_title: CHAPTER_TITLES[6],
    pattern_ko: "A에게 ~라고 말해주다",
    pattern_en: "tell A (that) ~",
    example_dialogue: [
      { speaker: "E", text_en: "Tell him that I'll be late.", text_ko: "그에게 늦는다고 말해줘." },
      { speaker: "K", text_en: "Okay, I'll let him know.", text_ko: "알겠어, 전할게." },
    ],
  },
  {
    id: 86,
    chapter_num: 6,
    chapter_title: CHAPTER_TITLES[6],
    pattern_ko: "A가 ~하는 걸 도와주다",
    pattern_en: "help A (to) ~",
    example_dialogue: [
      { speaker: "E", text_en: "Can you help me move this?", text_ko: "이거 옮기는 거 도와줄래?" },
      { speaker: "K", text_en: "Sure, no problem.", text_ko: "그럼, 문제없어." },
    ],
  },
  {
    id: 87,
    chapter_num: 6,
    chapter_title: CHAPTER_TITLES[6],
    pattern_ko: "…배 ~한",
    pattern_en: "… times as ~ as",
    example_dialogue: [
      { speaker: "E", text_en: "This is three times as big as that.", text_ko: "이건 저것보다 세 배 커." },
      { speaker: "K", text_en: "Wow, that's huge.", text_ko: "와, 엄청 크다." },
    ],
  },
  {
    id: 88,
    chapter_num: 6,
    chapter_title: CHAPTER_TITLES[6],
    pattern_ko: "A를 ~하게 하다",
    pattern_en: "make A ~",
    example_dialogue: [
      { speaker: "E", text_en: "That makes me happy.", text_ko: "그건 날 행복하게 해." },
      { speaker: "K", text_en: "I'm glad.", text_ko: "다행이야." },
    ],
  },
  {
    id: 89,
    chapter_num: 6,
    chapter_title: CHAPTER_TITLES[6],
    pattern_ko: "A더러 ~하도록 시키다",
    pattern_en: "have[get] A ~ [to ~]",
    example_dialogue: [
      { speaker: "E", text_en: "I'll have him call you back.", text_ko: "그에게 다시 전화하도록 할게요." },
      { speaker: "K", text_en: "Thank you.", text_ko: "감사합니다." },
    ],
  },
  {
    id: 90,
    chapter_num: 6,
    chapter_title: CHAPTER_TITLES[6],
    pattern_ko: "내가 처음 ~했을때",
    pattern_en: "When I first ~",
    example_dialogue: [
      { speaker: "E", text_en: "When I first met her, I was nervous.", text_ko: "그녀를 처음 만났을 때 긴장했어." },
      { speaker: "K", text_en: "That's cute.", text_ko: "귀엽다." },
    ],
  },
  {
    id: 91,
    chapter_num: 6,
    chapter_title: CHAPTER_TITLES[6],
    pattern_ko: "A가 ~하기를 원하다",
    pattern_en: "want A to ~",
    example_dialogue: [
      { speaker: "E", text_en: "I want you to be happy.", text_ko: "네가 행복하길 원해." },
      { speaker: "K", text_en: "That's sweet.", text_ko: "다정하네." },
    ],
  },
  {
    id: 92,
    chapter_num: 6,
    chapter_title: CHAPTER_TITLES[6],
    pattern_ko: "A가 ~하는 것을/~된 것을 보다",
    pattern_en: "see A -ing/PP",
    example_dialogue: [
      { speaker: "E", text_en: "I saw him running this morning.", text_ko: "오늘 아침 그가 뛰는 걸 봤어." },
      { speaker: "K", text_en: "He exercises a lot.", text_ko: "운동 많이 하네." },
    ],
  },
  {
    id: 93,
    chapter_num: 6,
    chapter_title: CHAPTER_TITLES[6],
    pattern_ko: "…하나 ~하나 마찬가지다",
    pattern_en: "It's the same whether … or ~",
    example_dialogue: [
      { speaker: "E", text_en: "It's the same whether we go now or later.", text_ko: "지금 가나 나중에 가나 마찬가지야." },
      { speaker: "K", text_en: "Then let's go now.", text_ko: "그럼 지금 가자." },
    ],
  },
  {
    id: 94,
    chapter_num: 6,
    chapter_title: CHAPTER_TITLES[6],
    pattern_ko: "A가 ~되도록 하다",
    pattern_en: "get A ~",
    example_dialogue: [
      { speaker: "E", text_en: "I'll get the report done by noon.", text_ko: "보고서를 정오까지 되도록 할게요." },
      { speaker: "K", text_en: "Great, thanks.", text_ko: "좋아요, 고마워요." },
    ],
  },
  {
    id: 95,
    chapter_num: 6,
    chapter_title: CHAPTER_TITLES[6],
    pattern_ko: "~에 익숙하다",
    pattern_en: "be used to ~",
    example_dialogue: [
      { speaker: "E", text_en: "I'm used to waking up early.", text_ko: "일찍 일어나는 데 익숙해." },
      { speaker: "K", text_en: "I could never do that.", text_ko: "난 절대 못 해." },
    ],
  },
  {
    id: 96,
    chapter_num: 6,
    chapter_title: CHAPTER_TITLES[6],
    pattern_ko: "~하는 식으로",
    pattern_en: "the way ~",
    example_dialogue: [
      { speaker: "E", text_en: "I like the way you think.", text_ko: "네가 생각하는 방식이 좋아." },
      { speaker: "K", text_en: "Thank you.", text_ko: "고마워." },
    ],
  },
  {
    id: 97,
    chapter_num: 6,
    chapter_title: CHAPTER_TITLES[6],
    pattern_ko: "그렇게 ~한 건 처음 봤어",
    pattern_en: "I've never seen such a[an] ~",
    example_dialogue: [
      { speaker: "E", text_en: "I've never seen such a beautiful view.", text_ko: "그렇게 아름다운 풍경은 처음 봤어." },
      { speaker: "K", text_en: "It's breathtaking.", text_ko: "숨 막히게 멋지지." },
    ],
  },
  {
    id: 98,
    chapter_num: 6,
    chapter_title: CHAPTER_TITLES[6],
    pattern_ko: "A가 ~하기를/되기를 바라다",
    pattern_en: "want A ~",
    example_dialogue: [
      { speaker: "E", text_en: "I want this finished today.", text_ko: "이게 오늘 끝나기를 바라." },
      { speaker: "K", text_en: "We'll do our best.", text_ko: "최선을 다할게요." },
    ],
  },
  {
    id: 99,
    chapter_num: 6,
    chapter_title: CHAPTER_TITLES[6],
    pattern_ko: "~처럼 들리다",
    pattern_en: "sound like ~",
    example_dialogue: [
      { speaker: "E", text_en: "That sounds like a great idea.", text_ko: "그거 좋은 생각처럼 들려." },
      { speaker: "K", text_en: "Let's do it.", text_ko: "그렇게 하자." },
    ],
  },
  {
    id: 100,
    chapter_num: 6,
    chapter_title: CHAPTER_TITLES[6],
    pattern_ko: "~처럼 보이다",
    pattern_en: "look like ~",
    example_dialogue: [
      { speaker: "E", text_en: "It looks like rain.", text_ko: "비가 올 것처럼 보여." },
      { speaker: "K", text_en: "Let's stay in.", text_ko: "그냥 집에 있자." },
    ],
  },
  {
    id: 101,
    chapter_num: 6,
    chapter_title: CHAPTER_TITLES[6],
    pattern_ko: "A가 ~하도록 허락하다",
    pattern_en: "let A ~",
    example_dialogue: [
      { speaker: "E", text_en: "Let me explain.", text_ko: "내가 설명하게 해줘." },
      { speaker: "K", text_en: "Go ahead.", text_ko: "말해 봐." },
    ],
  },
  {
    id: 102,
    chapter_num: 6,
    chapter_title: CHAPTER_TITLES[6],
    pattern_ko: "A를 권해서 ~하게 하다",
    pattern_en: "encourage A to ~",
    example_dialogue: [
      { speaker: "E", text_en: "My teacher encouraged me to try.", text_ko: "선생님이 날 권해서 도전하게 했어." },
      { speaker: "K", text_en: "That's wonderful.", text_ko: "멋지다." },
    ],
  },
  {
    id: 103,
    chapter_num: 6,
    chapter_title: CHAPTER_TITLES[6],
    pattern_ko: "~인지 아닌지",
    pattern_en: "whether ~ or not",
    example_dialogue: [
      { speaker: "E", text_en: "I'm going whether you come or not.", text_ko: "네가 오든 안 오든 난 갈 거야." },
      { speaker: "K", text_en: "Then I'll come.", text_ko: "그럼 나도 갈게." },
    ],
  },
  {
    id: 104,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "무엇을 ~하더라도",
    pattern_en: "No matter what ~",
    example_dialogue: [
      { speaker: "E", text_en: "No matter what happens, I'll support you.", text_ko: "무슨 일이 있어도 널 응원할게." },
      { speaker: "K", text_en: "Thank you, that means a lot.", text_ko: "고마워, 큰 힘이 돼." },
    ],
  },
  {
    id: 105,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~얘기가 나와서 말인데",
    pattern_en: "Speaking of ~",
    example_dialogue: [
      { speaker: "E", text_en: "Speaking of food, I'm hungry.", text_ko: "음식 얘기가 나와서 말인데, 나 배고파." },
      { speaker: "K", text_en: "Let's grab lunch.", text_ko: "점심 먹으러 가자." },
    ],
  },
  {
    id: 106,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "A가 ~하다시피",
    pattern_en: "As A ~",
    example_dialogue: [
      { speaker: "E", text_en: "As you know, the deadline is tomorrow.", text_ko: "너도 알다시피 마감이 내일이야." },
      { speaker: "K", text_en: "I'm almost done.", text_ko: "거의 다 했어." },
    ],
  },
  {
    id: 107,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~에도 불구하고",
    pattern_en: "In spite of ~",
    example_dialogue: [
      { speaker: "E", text_en: "In spite of the rain, we went out.", text_ko: "비에도 불구하고 우리는 나갔어." },
      { speaker: "K", text_en: "That's dedication.", text_ko: "대단한 의지네." },
    ],
  },
  {
    id: 108,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~하기만 하다면",
    pattern_en: "As long as ~",
    example_dialogue: [
      { speaker: "E", text_en: "As long as you're happy, I'm happy.", text_ko: "네가 행복하기만 하면 나도 행복해." },
      { speaker: "K", text_en: "That's kind of you.", text_ko: "다정하네." },
    ],
  },
  {
    id: 109,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~에 비해서",
    pattern_en: "Compared to ~",
    example_dialogue: [
      { speaker: "E", text_en: "Compared to last year, sales are up.", text_ko: "작년에 비해서 매출이 올랐어." },
      { speaker: "K", text_en: "Great news!", text_ko: "좋은 소식이네!" },
    ],
  },
  {
    id: 110,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~에 관한 한",
    pattern_en: "As far as ~ is concerned",
    example_dialogue: [
      { speaker: "E", text_en: "As far as I'm concerned, it's fine.", text_ko: "내가 보기에는 괜찮아." },
      { speaker: "K", text_en: "Good to hear.", text_ko: "다행이다." },
    ],
  },
  {
    id: 111,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~하기는커녕",
    pattern_en: "Far from ~",
    example_dialogue: [
      { speaker: "E", text_en: "He's far from lazy.", text_ko: "그는 게으르기는커녕 부지런해." },
      { speaker: "K", text_en: "I noticed that.", text_ko: "나도 느꼈어." },
    ],
  },
  {
    id: 112,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "마치 ~인 것처럼",
    pattern_en: "as if ~",
    example_dialogue: [
      { speaker: "E", text_en: "He acts as if he knows everything.", text_ko: "그는 마치 모든 걸 아는 것처럼 행동해." },
      { speaker: "K", text_en: "That's annoying.", text_ko: "짜증 나네." },
    ],
  },
  {
    id: 113,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~에 관한 한",
    pattern_en: "When it comes to ~",
    example_dialogue: [
      { speaker: "E", text_en: "When it comes to cooking, she's the best.", text_ko: "요리에 관한 한 그녀가 최고야." },
      { speaker: "K", text_en: "I'd love to taste it.", text_ko: "맛보고 싶다." },
    ],
  },
  {
    id: 114,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~하지 그래?",
    pattern_en: "Why don't you ~?",
    example_dialogue: [
      { speaker: "E", text_en: "Why don't you take a break?", text_ko: "좀 쉬지 그래?" },
      { speaker: "K", text_en: "Good idea, I will.", text_ko: "좋은 생각이야, 그럴게." },
    ],
  },
  {
    id: 115,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~하자/~할까?",
    pattern_en: "Why don't we ~?",
    example_dialogue: [
      { speaker: "E", text_en: "Why don't we go for a walk?", text_ko: "우리 산책하자." },
      { speaker: "K", text_en: "Sure, let's go.", text_ko: "좋아, 가자." },
    ],
  },
  {
    id: 116,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~대신에",
    pattern_en: "instead of ~",
    example_dialogue: [
      { speaker: "E", text_en: "Let's walk instead of driving.", text_ko: "운전하는 대신에 걷자." },
      { speaker: "K", text_en: "Good, it's a nice day.", text_ko: "좋아, 날씨 좋아." },
    ],
  },
  {
    id: 117,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "아마 ~일 거다",
    pattern_en: "Chances are ~",
    example_dialogue: [
      { speaker: "E", text_en: "Chances are he's already home.", text_ko: "아마 그는 벌써 집에 있을 거야." },
      { speaker: "K", text_en: "Let's call to check.", text_ko: "전화해 보자." },
    ],
  },
  {
    id: 118,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~도 당연하다/어쩐지 ~하더라",
    pattern_en: "No wonder ~",
    example_dialogue: [
      { speaker: "E", text_en: "No wonder you're tired.", text_ko: "어쩐지 네가 피곤하더라." },
      { speaker: "K", text_en: "I barely slept.", text_ko: "거의 못 잤어." },
    ],
  },
  {
    id: 119,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~가는[오는] 길에",
    pattern_en: "on the way to ~",
    example_dialogue: [
      { speaker: "E", text_en: "I'll buy milk on the way home.", text_ko: "집에 가는 길에 우유 살게." },
      { speaker: "K", text_en: "Thanks!", text_ko: "고마워!" },
    ],
  },
  {
    id: 120,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~하는 데 얼마나 걸립니까?",
    pattern_en: "How long does it take to ~?",
    example_dialogue: [
      { speaker: "E", text_en: "How long does it take to get there?", text_ko: "거기 가는 데 얼마나 걸려?" },
      { speaker: "K", text_en: "About thirty minutes.", text_ko: "30분쯤." },
    ],
  },
  {
    id: 121,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "제가 ~해도 괜찮을까요?",
    pattern_en: "Do you mind if I ~?",
    example_dialogue: [
      { speaker: "E", text_en: "Do you mind if I sit here?", text_ko: "제가 여기 앉아도 괜찮을까요?" },
      { speaker: "K", text_en: "Not at all.", text_ko: "그럼요, 앉으세요." },
    ],
  },
  {
    id: 122,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "네 말은 ~라는 거니?",
    pattern_en: "You mean ~?",
    example_dialogue: [
      { speaker: "E", text_en: "You mean we're leaving now?", text_ko: "네 말은 지금 떠난다는 거니?" },
      { speaker: "K", text_en: "Yes, right now.", text_ko: "응, 지금 바로." },
    ],
  },
  {
    id: 123,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~하는 버릇이 있다",
    pattern_en: "have a habit of -ing",
    example_dialogue: [
      { speaker: "E", text_en: "I have a habit of biting my nails.", text_ko: "손톱을 깨무는 버릇이 있어." },
      { speaker: "K", text_en: "Try to stop it.", text_ko: "고쳐 보도록 해." },
    ],
  },
  {
    id: 124,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~하느라 힘들다",
    pattern_en: "have a hard time -ing",
    example_dialogue: [
      { speaker: "E", text_en: "I have a hard time waking up early.", text_ko: "일찍 일어나느라 힘들어." },
      { speaker: "K", text_en: "Set more alarms.", text_ko: "알람을 더 맞춰." },
    ],
  },
  {
    id: 125,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "막 ~하려고 하다",
    pattern_en: "be about to ~",
    example_dialogue: [
      { speaker: "E", text_en: "I was about to call you.", text_ko: "막 너한테 전화하려던 참이었어." },
      { speaker: "K", text_en: "Great timing!", text_ko: "타이밍 좋네!" },
    ],
  },
  {
    id: 126,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "예전에 ~했었다",
    pattern_en: "used to ~",
    example_dialogue: [
      { speaker: "E", text_en: "I used to play the piano.", text_ko: "예전에 피아노를 쳤었어." },
      { speaker: "K", text_en: "You should start again.", text_ko: "다시 시작해 봐." },
    ],
  },
  {
    id: 127,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~에 질리다",
    pattern_en: "be sick of ~",
    example_dialogue: [
      { speaker: "E", text_en: "I'm sick of this rainy weather.", text_ko: "이 비 오는 날씨에 질렸어." },
      { speaker: "K", text_en: "Me too, I miss the sun.", text_ko: "나도, 햇빛이 그리워." },
    ],
  },
  {
    id: 128,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "기꺼이 ~할 마음이 있다",
    pattern_en: "be willing to ~",
    example_dialogue: [
      { speaker: "E", text_en: "I'm willing to help anytime.", text_ko: "언제든 기꺼이 도울 마음이 있어." },
      { speaker: "K", text_en: "You're a good friend.", text_ko: "좋은 친구야." },
    ],
  },
  {
    id: 129,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~을 걱정하다",
    pattern_en: "be worried (that)/about",
    example_dialogue: [
      { speaker: "E", text_en: "I'm worried about the exam.", text_ko: "시험이 걱정돼." },
      { speaker: "K", text_en: "You'll do fine.", text_ko: "잘할 거야." },
    ],
  },
  {
    id: 130,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~을 어떻게 해 드릴까요?",
    pattern_en: "How would you like your ~?",
    example_dialogue: [
      { speaker: "E", text_en: "How would you like your steak?", text_ko: "스테이크를 어떻게 해 드릴까요?" },
      { speaker: "K", text_en: "Medium, please.", text_ko: "미디엄으로요." },
    ],
  },
  {
    id: 131,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "내가 장담하는데 ~일 거다",
    pattern_en: "I bet ~",
    example_dialogue: [
      { speaker: "E", text_en: "I bet you'll pass the test.", text_ko: "내가 장담하는데 너 시험 붙을 거야." },
      { speaker: "K", text_en: "I hope you're right.", text_ko: "그러길 바라." },
    ],
  },
  {
    id: 132,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "(감히) 네가 어떻게 ~할 수 있니?",
    pattern_en: "How dare you ~?",
    example_dialogue: [
      { speaker: "E", text_en: "How dare you say that!", text_ko: "네가 어떻게 그런 말을 할 수 있니!" },
      { speaker: "K", text_en: "I'm sorry, I went too far.", text_ko: "미안, 너무했어." },
    ],
  },
  {
    id: 133,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~와 아무 관련이 없다",
    pattern_en: "have nothing to do with ~",
    example_dialogue: [
      { speaker: "E", text_en: "I have nothing to do with this.", text_ko: "난 이 일과 아무 관련이 없어." },
      { speaker: "K", text_en: "Okay, I believe you.", text_ko: "알겠어, 믿어." },
    ],
  },
  {
    id: 134,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~만큼 …하지는 않은",
    pattern_en: "not as … as ~",
    example_dialogue: [
      { speaker: "E", text_en: "This isn't as hard as it looks.", text_ko: "이건 보기만큼 어렵지 않아." },
      { speaker: "K", text_en: "That's a relief.", text_ko: "다행이다." },
    ],
  },
  {
    id: 135,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~하면 어쩌지?",
    pattern_en: "What if ~?",
    example_dialogue: [
      { speaker: "E", text_en: "What if it doesn't work?", text_ko: "안 되면 어쩌지?" },
      { speaker: "K", text_en: "Then we'll try again.", text_ko: "그럼 다시 해보지." },
    ],
  },
  {
    id: 136,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~라는 걸 인정해야겠군요",
    pattern_en: "I must admit (that) ~",
    example_dialogue: [
      { speaker: "E", text_en: "I must admit that you were right.", text_ko: "네 말이 맞았다는 걸 인정해야겠어." },
      { speaker: "K", text_en: "Thank you for saying so.", text_ko: "그렇게 말해줘서 고마워." },
    ],
  },
  {
    id: 137,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~하기에 충분히 …한",
    pattern_en: "… enough to ~",
    example_dialogue: [
      { speaker: "E", text_en: "She's old enough to drive.", text_ko: "그녀는 운전할 만큼 충분히 나이가 들었어." },
      { speaker: "K", text_en: "Time flies.", text_ko: "세월 빠르다." },
    ],
  },
  {
    id: 138,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "~하고 싶은 기분이 든다",
    pattern_en: "be in the mood for ~",
    example_dialogue: [
      { speaker: "E", text_en: "I'm in the mood for some coffee.", text_ko: "커피 한잔 하고 싶은 기분이야." },
      { speaker: "K", text_en: "Let's get some.", text_ko: "마시러 가자." },
    ],
  },
  {
    id: 139,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "A에게 ~만큼 빚지다",
    pattern_en: "owe A ~",
    example_dialogue: [
      { speaker: "E", text_en: "I owe you a big favor.", text_ko: "너에게 큰 신세를 졌어." },
      { speaker: "K", text_en: "Don't mention it.", text_ko: "별말씀을." },
    ],
  },
  {
    id: 140,
    chapter_num: 7,
    chapter_title: CHAPTER_TITLES[7],
    pattern_ko: "…라고 해서 반드시~인 것은 아니다",
    pattern_en: "Just because …, it doesn't follow (that) ~",
    example_dialogue: [
      { speaker: "E", text_en: "Just because he's rich, it doesn't follow that he's happy.", text_ko: "그가 부자라고 해서 반드시 행복한 것은 아니야." },
      { speaker: "K", text_en: "That's very true.", text_ko: "정말 맞는 말이야." },
    ],
  },
];

export const ORDERED_PATTERNS = [...PATTERNS].sort((a, b) => a.id - b.id);

export function getPatternById(id: number): PatternData | undefined {
  return PATTERNS.find((p) => p.id === id);
}

export function getAdjacentPatterns(id: number): {
  prev: PatternData | null;
  next: PatternData | null;
} {
  const idx = ORDERED_PATTERNS.findIndex((p) => p.id === id);
  return {
    prev: idx > 0 ? ORDERED_PATTERNS[idx - 1] : null,
    next:
      idx >= 0 && idx < ORDERED_PATTERNS.length - 1
        ? ORDERED_PATTERNS[idx + 1]
        : null,
  };
}

export function formatNo(id: number): string {
  return String(id).padStart(3, "0");
}
